import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NextLink from 'next/link'
import { Link, Typography } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>ECO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1>ECO Store</h1>

        <NextLink href={`/`}>
          <Typography>Web</Typography>
        </NextLink>

        <NextLink href={`/dashboard`}>
          <Typography>Dashboard</Typography>
        </NextLink>

      </main>
    </>
  )
}
